IF EXISTS (SELECT SCHEMA_NAME FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'mycos-todo-db')
	RETURN

CREATE DATABASE [mycos-todo-db]  WITH CATALOG_COLLATION = SQL_Latin1_General_CP1_CI_AS;
GO

ALTER DATABASE [mycos-todo-db] SET ANSI_NULL_DEFAULT OFF 
GO

ALTER DATABASE [mycos-todo-db] SET ANSI_NULLS OFF 
GO

ALTER DATABASE [mycos-todo-db] SET ANSI_PADDING OFF 
GO

ALTER DATABASE [mycos-todo-db] SET ANSI_WARNINGS OFF 
GO

ALTER DATABASE [mycos-todo-db] SET ARITHABORT OFF 
GO

ALTER DATABASE [mycos-todo-db] SET AUTO_SHRINK OFF 
GO

ALTER DATABASE [mycos-todo-db] SET AUTO_UPDATE_STATISTICS ON 
GO

ALTER DATABASE [mycos-todo-db] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO

ALTER DATABASE [mycos-todo-db] SET CONCAT_NULL_YIELDS_NULL OFF 
GO

ALTER DATABASE [mycos-todo-db] SET NUMERIC_ROUNDABORT OFF 
GO

ALTER DATABASE [mycos-todo-db] SET QUOTED_IDENTIFIER OFF 
GO

ALTER DATABASE [mycos-todo-db] SET RECURSIVE_TRIGGERS OFF 
GO

ALTER DATABASE [mycos-todo-db] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO

ALTER DATABASE [mycos-todo-db] SET ALLOW_SNAPSHOT_ISOLATION ON 
GO

ALTER DATABASE [mycos-todo-db] SET PARAMETERIZATION SIMPLE 
GO

ALTER DATABASE [mycos-todo-db] SET READ_COMMITTED_SNAPSHOT ON 
GO

ALTER DATABASE [mycos-todo-db] SET  MULTI_USER 
GO

ALTER DATABASE [mycos-todo-db] SET QUERY_STORE = ON
GO

ALTER DATABASE [mycos-todo-db] SET QUERY_STORE (OPERATION_MODE = READ_WRITE, CLEANUP_POLICY = (STALE_QUERY_THRESHOLD_DAYS = 7), DATA_FLUSH_INTERVAL_SECONDS = 900, INTERVAL_LENGTH_MINUTES = 60, MAX_STORAGE_SIZE_MB = 10, QUERY_CAPTURE_MODE = AUTO, SIZE_BASED_CLEANUP_MODE = AUTO, MAX_PLANS_PER_QUERY = 200, WAIT_STATS_CAPTURE_MODE = ON)
GO

/*** The scripts of database scoped configurations in Azure should be executed inside the target database connection. ***/
GO

-- ALTER DATABASE SCOPED CONFIGURATION SET MAXDOP = 8;
GO

ALTER DATABASE [mycos-todo-db] SET  READ_WRITE 
GO

SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

USE [mycos-todo-db]
GO

IF NOT EXISTS (SELECT * FROM dbo.sysobjects where id = object_id(N'[SH_ResetPasswordURL]') and OBJECTPROPERTY(id, N'IsUserTable') = 1)
BEGIN
	CREATE TABLE [dbo].[Todo_list](
		[id] [int] IDENTITY(1,1) NOT NULL,
		[text] [nvarchar](max) NOT NULL,
		[status] [tinyint] NOT NULL
	) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
END
GO